# Generated by Django 5.0.7 on 2024-10-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_auto_20240929_2041"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="gst_no",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
