# Generated by Django 3.0.8 on 2024-09-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoice_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
